# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import rune_pb2 as rune_dot_wire_dot_v1_dot_rune__pb2


class RuneServiceStub(object):
    """Caster 与 Runtime 的双向流
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/rune.wire.v1.RuneService/Session',
                request_serializer=rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.SerializeToString,
                response_deserializer=rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.FromString,
                )


class RuneServiceServicer(object):
    """Caster 与 Runtime 的双向流
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.FromString,
                    response_serializer=rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rune.wire.v1.RuneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RuneService(object):
    """Caster 与 Runtime 的双向流
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/rune.wire.v1.RuneService/Session',
            rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.SerializeToString,
            rune_dot_wire_dot_v1_dot_rune__pb2.SessionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
